# Generated by Django 2.1.5 on 2020-06-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_byindians'),
    ]

    operations = [
        migrations.AddField(
            model_name='byindians',
            name='channelname',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='byindians',
            name='date_published',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='byindians',
            name='dislikes',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='byindians',
            name='likes',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='byindians',
            name='title',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='byindians',
            name='views',
            field=models.IntegerField(default=''),
        ),
    ]
