# Generated by Django 2.1.5 on 2020-06-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200628_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byindians',
            name='channelname',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='byindians',
            name='date_published',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='byindians',
            name='dislikes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='byindians',
            name='likes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='byindians',
            name='title',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='byindians',
            name='views',
            field=models.IntegerField(),
        ),
    ]
