# Generated by Django 2.1.5 on 2020-06-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200628_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='byindian',
            name='channelname',
        ),
    ]
