# Generated by Django 2.1.5 on 2020-06-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_byindian_channelname'),
    ]

    operations = [
        migrations.CreateModel(
            name='byindians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('views', models.IntegerField()),
                ('date_published', models.CharField(max_length=20)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='byindian',
        ),
    ]
