# Generated by Django 2.1.5 on 2020-06-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20200628_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='byindians',
            name='channelname',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='byindians',
            name='date_published',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='byindians',
            name='title',
            field=models.CharField(default='', max_length=800),
        ),
    ]
