# Generated by Django 2.1.5 on 2020-06-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20200628_2324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='byindian',
        ),
    ]
