# Generated by Django 2.1.5 on 2020-06-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_byindian'),
    ]

    operations = [
        migrations.CreateModel(
            name='byindians',
            fields=[
                ('title', models.CharField(max_length=800)),
                ('published_at', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('channel', models.CharField(max_length=200)),
                ('view_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('dislike_count', models.IntegerField()),
                ('favorite_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=800)),
                ('categories', models.CharField(max_length=800)),
                ('video_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='byindian',
        ),
    ]
